import = [
    "~/.config/alacritty/themes/catppuccin-macchiato.toml",
    # "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 140, lines = 40 }
padding.x = 10
padding.y = 10

decorations = "Buttonless"

# opacity = 0.8
# blur = true

[font]
normal.family = "MesloLGS NF"

size = 14

