"$schema" = "https://starship.rs/config-schema.json"

format = """$directory$character"""
right_format = """
$git_branch\
$git_status\
$docker_context\
$nodejs\
$python\
$cmd_duration\
"""

palette = "catppuccin_mocha"

add_newline = false

command_timeout = 1000

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[directory]
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "…/"
read_only = " "

[directory.substitutions]
"~/Documents/projects/personal" = "…/personal"
"~/Documents/projects/dxc/helix" = "…/helix"

[git_branch]
symbol = ""
format = "[ $symbol $branch]($style)"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[nodejs]
symbol = ""
format = "[ $symbol $version]($style)"

[python]
symbol = ""
format = "[ $symbol $version]($style)"

[docker_context]
symbol = ""
format = "[ $symbol $context]($style)"
disabled = true

[cmd_duration]
format = " took [$duration]($style)"
